/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Views;

import Controllers.MarcaJpaController;
import Controllers.ProductoJpaController;
import Entitys.Marca;
import Entitys.Producto;
import Views.Settings.ClaseJcombobox;
import Views.Settings.MT;
import Views.Settings.TableColumnAdjuster;
import Views.Settings.Ventana;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Gabriel
 */
public class frmMantProductos extends Ventana {
    
    private static frmMantProductos instancia; 
    List<Producto> listaProductos = new ArrayList<>();
    Producto oproducto;

    /**
     * Creates new form frmListProductos
     */
    public frmMantProductos() {
        initComponents();
        this.presentarDatos("CargarCombo");
        this.presentarDatos(); 
    }  
    
    public static frmMantProductos getInstancia() {
        if (instancia == null) {
            instancia = new frmMantProductos();
        }
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxMarca = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductoList = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxMarca2 = new javax.swing.JComboBox();
        txtCodigo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion2 = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jFormattedPrecioVenta = new javax.swing.JFormattedTextField();
        btnNext = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones Busqueda"));

        jLabel1.setText("Descripción:");

        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyPressed(evt);
            }
        });

        jLabel2.setText("Marca:");

        jComboBoxMarca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jComboBoxMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMarcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Productos"));

        jTableProductoList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProductoList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro Producto"));

        jLabel3.setText("Marca:");

        jLabel4.setText("Descripcion:");

        jLabel5.setText("Codigo:");

        jLabel6.setText("PrecioVenta:");

        jComboBoxMarca2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        txtDescripcion2.setColumns(20);
        txtDescripcion2.setRows(5);
        jScrollPane2.setViewportView(txtDescripcion2);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jFormattedPrecioVenta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        btnNext.setIcon(new javax.swing.ImageIcon("Images/next-button_opt.jpg"));
        btnNext.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 51), null));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon("Images/cancelacion_opt.png"));
        btnCancel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 204, 51), null));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnNext)
                        .addGap(169, 169, 169)
                        .addComponent(btnCancel))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jComboBoxMarca2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(32, 32, 32)
                                .addComponent(btnModificar))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                .addComponent(jFormattedPrecioVenta, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxMarca2))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnNext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMarcaActionPerformed
        // TODO add your handling code here:   
        while(this.listaProductos.size()>0)this.listaProductos.remove(0);
        if (jComboBoxMarca.getSelectedIndex() == 0) {
            this.presentarDatos();
        } else {
            ClaseJcombobox cjbxMarca = (ClaseJcombobox) jComboBoxMarca.getSelectedItem();
            Marca omarca = new Marca();
            omarca.setIdMarca(cjbxMarca.getTipoid());             
            listaProductos = controladorProducto.buscarXMarca(omarca);            
            this.presentarDatos("CargarTabla");
        } 
        
        
    }//GEN-LAST:event_jComboBoxMarcaActionPerformed

    private void txtDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyPressed
        // TODO add your handling code here:        
        if (!txtDescripcion.getText().equals("")) {
            while(this.listaProductos.size()>0)this.listaProductos.remove(0);
            this.listaProductos = controladorProducto.buscarXDescripcion(txtDescripcion.getText());
            this.presentarDatos("CargarTabla");
        } else {
            this.presentarDatos();
        }   
        
    }//GEN-LAST:event_txtDescripcionKeyPressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:      
        if (jComboBoxMarca2.getSelectedIndex()!=0 && !"".equals(txtCodigo.getText()) && !"".equals(txtDescripcion2.getText())) {
            int opcion =  JOptionPane.showConfirmDialog(this,"¿Desea Agregar Este Producto?");
            if(opcion == JOptionPane.OK_OPTION){ 
            Producto oproducto = new Producto();
            ClaseJcombobox cjbxMarca = (ClaseJcombobox) jComboBoxMarca2.getSelectedItem();
            Marca omarca = new Marca();
            omarca.setIdMarca(cjbxMarca.getTipoid());            
            oproducto.setCodigo(txtCodigo.getText());
            oproducto.setDescripcion(txtDescripcion2.getText());            
            BigDecimal bd=new BigDecimal(jFormattedPrecioVenta.getText().replaceAll(",","."));            
            oproducto.setPrecioventa(bd);
            System.out.println(oproducto.getPrecioventa());
            oproducto.setIdMarca(omarca);
            try {
                controladorProducto.create(oproducto);
            } catch (Exception ex) {
                Logger.getLogger(frmMantProductos.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Producto Registrado Correctamente", "Mensaje del Sistema", JOptionPane.INFORMATION_MESSAGE);
            this.presentarDatos();
            this.limpiarFormulario();
            }            
            
        } else {
            JOptionPane.showMessageDialog(null, "Error: Faltan Ingresar Datos", "Mensaje del Sistema", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:        
         if (jTableProductoList.getSelectedRow() != -1) { 
            btnModificar.setEnabled(true);btnGuardar.setEnabled(false);
            oproducto =  (Producto) ((MT)jTableProductoList.getModel()).getSeleccion(jTableProductoList.getSelectedRow()); 
            jComboBoxMarca2.setSelectedIndex(oproducto.getIdMarca().hashCode());
            txtDescripcion2.setText(oproducto.getDescripcion());
            txtCodigo.setText(oproducto.getCodigo());
            BigDecimal bigDecimal = new BigDecimal(oproducto.getPrecioventa().toString()); 
            jFormattedPrecioVenta.setText(bigDecimal.toString());            
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un Producto","Mensaje del Sistema", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        if (jComboBoxMarca2.getSelectedIndex() != 0 && !"".equals(txtCodigo.getText()) && !"".equals(txtDescripcion2.getText())) {
            int opcion = JOptionPane.showConfirmDialog(this, "¿Desea Modifcar Este Producto?");
            if (opcion == JOptionPane.OK_OPTION) {
                ClaseJcombobox cjbxMarca = (ClaseJcombobox) jComboBoxMarca2.getSelectedItem();
                Marca omarca = new Marca();
                omarca.setIdMarca(cjbxMarca.getTipoid());
                oproducto.setCodigo(txtCodigo.getText());
                oproducto.setDescripcion(txtDescripcion2.getText());
                BigDecimal bd = new BigDecimal(jFormattedPrecioVenta.getText().replaceAll(",", "."));
                oproducto.setPrecioventa(bd);
                System.out.println(oproducto.getPrecioventa());
                oproducto.setIdMarca(omarca);
                oproducto.setIdProducto(oproducto.getIdProducto());
                try {
                    controladorProducto.edit(oproducto);
                } catch (Exception ex) {
                    Logger.getLogger(frmMantProductos.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(null, "Producto Modifcado Correctamente", "Mensaje del Sistema", JOptionPane.INFORMATION_MESSAGE);
                this.presentarDatos();
                this.limpiarFormulario();
                btnModificar.setEnabled(false);
                btnGuardar.setEnabled(true);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Error: Faltan Ingresar Datos", "Mensaje del Sistema", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.limpiarFormulario();
        btnGuardar.setEnabled(true);btnModificar.setEnabled(false);
        jFormattedPrecioVenta.setText("000000,00");        
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNext;
    private javax.swing.JComboBox jComboBoxMarca;
    private javax.swing.JComboBox jComboBoxMarca2;
    private javax.swing.JFormattedTextField jFormattedPrecioVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableProductoList;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextArea txtDescripcion2;
    // End of variables declaration//GEN-END:variables

    ProductoJpaController controladorProducto = new ProductoJpaController();
    MarcaJpaController controladorMarca = new MarcaJpaController();
    
    @Override
    public void presentarDatos() {
        this.listaProductos = controladorProducto.findProductoEntities();
        Object[][] datos = new Object[listaProductos.size()][4];
        for (int i = 0; i < listaProductos.size(); i++) { 
            datos[i][0] = listaProductos.get(i).getIdMarca().getNombre();
            datos[i][1] = listaProductos.get(i).getDescripcion();
            datos[i][2] = listaProductos.get(i).getCodigo();
            datos[i][3] = listaProductos.get(i).getPrecioventa();
        }
        String[] columnas = {"Marca","Descripcion", "Codigo", "PrecioUnit."};
        jTableProductoList.setModel(new MT(columnas, datos, listaProductos));
        jFormattedPrecioVenta.setText("000000,00");
        btnModificar.setEnabled(false);
        this.setAnchoColumnas();
    }

    @Override
    public void llenarCampos(Object objeto) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void presentarDatos(String opcion) {
        if(opcion.equals("CargarCombo")){
            List<Marca> listaMarcas = controladorMarca.findMarcaEntities();
            for (Marca listMarca1 : listaMarcas) {jComboBoxMarca.addItem(new ClaseJcombobox(listMarca1.getNombre(), listMarca1.getIdMarca()));}
            for (Marca listMarca1 : listaMarcas) {jComboBoxMarca2.addItem(new ClaseJcombobox(listMarca1.getNombre(), listMarca1.getIdMarca()));} 
        }else if(opcion.equals("CargarTabla")){            
            Object[][] datos = new Object[listaProductos.size()][4];
            for (int i = 0; i < listaProductos.size(); i++) {
                datos[i][0] = listaProductos.get(i).getIdMarca().getNombre();
                datos[i][1] = listaProductos.get(i).getDescripcion();
                datos[i][2] = listaProductos.get(i).getCodigo();
                datos[i][3] = listaProductos.get(i).getPrecioventa();
            }
            String[] columnas = {"Marca", "Descripcion", "Codigo", "PrecioUnit."};
            jTableProductoList.setModel(new MT(columnas, datos, listaProductos));
            this.setAnchoColumnas();            
        }
    }

    @Override
    public void llenarCampos(String opcion, Object objeto) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void limpiarFormulario() {
        jComboBoxMarca2.setSelectedIndex(0);
        txtDescripcion2.setText("");txtCodigo.setText("");jFormattedPrecioVenta.setText("");
    }
    
    public void setAnchoColumnas(){        
        jTableProductoList.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        TableColumnAdjuster tca = new TableColumnAdjuster(jTableProductoList);
        tca.adjustColumns();
        
    } 
}
