/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Views;

import Controllers.AreaJpaController;
import Controllers.ContactoJpaController;
import Controllers.DetalleOrdenJpaController;
import Controllers.OrdenCompraJpaController;
import Controllers.ProveedorJpaController;
import Controllers.TrabajadorJpaController;
import Entitys.Area;
import Entitys.Contacto;
import Entitys.DetalleOrden;
import Entitys.OrdenCompra;
import Entitys.Producto;
import Entitys.Proveedor;
import Entitys.Trabajador;
import Views.Settings.ClaseJcombobox;
import Views.Settings.MT_DetalleOrden;
import Views.Settings.TableColumnAdjuster;
import Views.Settings.Ventana;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jdesktop.observablecollections.ObservableList;

/**
 *
 * @author Gabriel
 */
public class frmRegistroOrdenCompra extends Ventana {
    
   private static frmRegistroOrdenCompra instancia;    
   List<Trabajador> listTrabajador= new ArrayList<>();
   List<Contacto> listContacto= new ArrayList<>(); 
   ObservableList<DetalleOrden> listDetalleOrden;
   
    
    
    /**
     * Creates new form frmRegistroOrdenCompra
     */
    public frmRegistroOrdenCompra() {
        initComponents();
        this.setLocation(Toolkit.getDefaultToolkit().getScreenSize().width / 2 - this.getWidth() / 2,Toolkit.getDefaultToolkit().getScreenSize().height / 2 - this.getHeight() / 2 );    
        this.presentarDatos();
        this.presentarDatos("TablaDetalleOrden");        
    }
    
    public static frmRegistroOrdenCompra getInstancia() {
        if (instancia == null) {
            instancia = new frmRegistroOrdenCompra();
        }
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxArea = new javax.swing.JComboBox();
        jComboBoxSolicitante = new javax.swing.JComboBox();
        txtSupervisor = new javax.swing.JTextField();
        txtProyecto = new javax.swing.JTextField();
        jDateChooserSolicitud = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxElaboradox = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxContacto = new javax.swing.JComboBox();
        jComboBoxProveedor = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDetalleOrden = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtnumorden = new javax.swing.JTextField();
        jComboBoxRefeCompra = new javax.swing.JComboBox();
        jComboBoxCondicionPago = new javax.swing.JComboBox();
        jComboBoxComprobPago = new javax.swing.JComboBox();
        jDateChooserEnvio = new com.toedter.calendar.JDateChooser();
        jDateChooserEntrega = new com.toedter.calendar.JDateChooser();
        jDateChooserRecepcion = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtsubtotal = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtigv = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jButtonListProductos = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jComboBoxMoneda = new javax.swing.JComboBox();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Area :");

        jLabel2.setText("Solicitante:");

        jLabel3.setText("Supervisor:");

        jLabel4.setText("Proyecto:");

        jLabel5.setText("Fecha de Solicitud:");

        jComboBoxArea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jComboBoxArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAreaActionPerformed(evt);
            }
        });

        jComboBoxSolicitante.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        jLabel11.setText("Elaborado Por:");

        jComboBoxElaboradox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4))
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jComboBoxElaboradox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSupervisor)
                            .addComponent(jComboBoxSolicitante, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxArea, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProyecto))
                        .addGap(216, 216, 216))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jDateChooserSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxArea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxSolicitante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSupervisor))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxElaboradox))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserSolicitud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(19, 19, 19))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("Proveedor:");

        jLabel8.setText("Contacto:");

        jComboBoxContacto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        jComboBoxProveedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jComboBoxProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProveedorActionPerformed(evt);
            }
        });

        jTableDetalleOrden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Marca", "Descripcion", "Garantia", "Unidad", "Cantidad", "PrecioUnit."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableDetalleOrden);

        btnEliminar.setIcon(new javax.swing.ImageIcon("Images/Remove_24x24.png"));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel8)
                        .addComponent(jComboBoxContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(640, 216));

        jLabel7.setText("Fecha Envio:");

        jLabel15.setText("Orden N°");

        txtnumorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumordenActionPerformed(evt);
            }
        });

        jComboBoxRefeCompra.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Cotizacion por Correo", "Num. de Cotizacion" }));

        jComboBoxCondicionPago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Cheque a 30 días", "Cheque a 60 días", "Cheque a 90 días", "Cheque a 105 días", "Contado" }));

        jComboBoxComprobPago.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Boleta de Pago", "Factura", "Recibo por Honorarios" }));

        jLabel9.setText("Fecha de Entrega:");

        jLabel10.setText("Fecha de Recepcion:");

        jLabel12.setText("Referencia de Compra:");

        jLabel13.setText("Condiciones de Pago:");

        jLabel14.setText("Comprobante de Pago:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                .addGap(26, 26, 26))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooserEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooserRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooserEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBoxCondicionPago, javax.swing.GroupLayout.Alignment.LEADING, 0, 347, Short.MAX_VALUE)
                                    .addComponent(jComboBoxComprobPago, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxRefeCompra, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGap(176, 176, 176)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtnumorden, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(36, 36, 36))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooserEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(txtnumorden)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooserEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooserRecepcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxRefeCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCondicionPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxComprobPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel19.setIcon(new javax.swing.ImageIcon("Images/ordenescompra_opt.png"));

        jLabel16.setText("SUB TOTAL:");

        jLabel17.setText("IGV:");

        jLabel18.setText("TOTAL:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        jButtonListProductos.setIcon(new javax.swing.ImageIcon("Images/Notepad.png"));
        jButtonListProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListProductosActionPerformed(evt);
            }
        });

        jLabel20.setText("Moneda:");

        jComboBoxMoneda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "$", "S/." }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 33, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20)
                            .addComponent(jButtonListProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtigv, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(txtsubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(jComboBoxMoneda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonListProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jComboBoxMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtigv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnCancelar))
                        .addGap(42, 42, 42))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnumordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumordenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumordenActionPerformed

    private void jComboBoxAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAreaActionPerformed
        // TODO add your handling code here:     
        
        jComboBoxSolicitante.removeAllItems();
        while(this.listTrabajador.size()>0)this.listTrabajador.remove(0);
        ClaseJcombobox cjbxArea = (ClaseJcombobox) jComboBoxArea.getSelectedItem();
        Area oarea = new Area();
        oarea.setIdArea(cjbxArea.getTipoid());
        listTrabajador = controladorTrabajador.buscarXAreas(oarea);
        for (Trabajador listTrabajador1 : listTrabajador) {
            jComboBoxSolicitante.addItem(new ClaseJcombobox(listTrabajador1.getNombres(), listTrabajador1.getIdTrabajador()));
        }
        txtSupervisor.setText(controladorTrabajador.buscarXResponsable(oarea).get(0).getApellidos()+" "+controladorTrabajador.buscarXResponsable(oarea).get(0).getNombres());
               
    }//GEN-LAST:event_jComboBoxAreaActionPerformed

    private void jComboBoxProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProveedorActionPerformed
        // TODO add your handling code here:
        jComboBoxContacto.removeAllItems();
        while(this.listContacto.size()>0)this.listContacto.remove(0);
        ClaseJcombobox cjbxProveedor = (ClaseJcombobox) jComboBoxProveedor.getSelectedItem();
        Proveedor oproveedor = new Proveedor();
        oproveedor.setIdProveedor(cjbxProveedor.getTipoid());
        listContacto = controladorContacto.buscarXProveedor(oproveedor);
        for (Contacto listContacto1 : listContacto) {
            jComboBoxContacto.addItem(new ClaseJcombobox(listContacto1.getNombre(), listContacto1.getIdContacto()));
        }
        
    }//GEN-LAST:event_jComboBoxProveedorActionPerformed

    private void jButtonListProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListProductosActionPerformed
        // TODO add your handling code here:
        frmListProductos lp = new frmListProductos(this);
        frmPrincipal.jDesktopPane1.add(lp);
        lp.toFront();
        lp.setVisible(true);
    }//GEN-LAST:event_jButtonListProductosActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
         if(jTableDetalleOrden.getSelectedRow() == -1 || jTableDetalleOrden.getSelectedRow() >= jTableDetalleOrden.getRowCount()){
          JOptionPane.showMessageDialog(this, "Seleccione un Producto","Mensaje del Sistema", JOptionPane.INFORMATION_MESSAGE);
        }else{
          int dato = jTableDetalleOrden.getSelectedRow();         
          this.listDetalleOrden.remove(dato);
          this.presentarDatos("TablaDetalleOrden");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        //////*****Guardando OrdenCompra*****////// 
        OrdenCompra ordenCompra = new OrdenCompra();        
        ordenCompra.setNumeroOrden(txtnumorden.getText());ordenCompra.setFechaSolicitud(jDateChooserSolicitud.getDate());
        ordenCompra.setFechaProcenvio(jDateChooserEnvio.getDate());ordenCompra.setFechaEntrega(jDateChooserEntrega.getDate());
        ordenCompra.setFechaRecepcion(jDateChooserRecepcion.getDate());ordenCompra.setNomProyecto(txtProyecto.getText());
        ordenCompra.setReferenciaCompra((String) jComboBoxRefeCompra.getModel().getSelectedItem());
        ordenCompra.setCondicionPago((String) jComboBoxCondicionPago.getModel().getSelectedItem());
        ordenCompra.setComprobantePago((String) jComboBoxComprobPago.getModel().getSelectedItem());
        ordenCompra.setMoneda((String) jComboBoxMoneda.getModel().getSelectedItem());
        //------->ObteniendoTrabajador<-------//
        Trabajador trabajador = new Trabajador();
        Contacto contacto = new Contacto();
        ClaseJcombobox cjbxTrabajador = (ClaseJcombobox) jComboBoxSolicitante.getSelectedItem();       
        trabajador.setIdTrabajador(cjbxTrabajador.getTipoid());
        ordenCompra.setIdSolicitante(trabajador);
        ClaseJcombobox cjbxTrabajador2 = (ClaseJcombobox) jComboBoxElaboradox.getSelectedItem();
        trabajador.setIdTrabajador(cjbxTrabajador2.getTipoid());
        ordenCompra.setIdElaborador(trabajador);
        ClaseJcombobox cjbxContacto = (ClaseJcombobox) jComboBoxContacto.getSelectedItem();
        contacto.setIdContacto(cjbxContacto.getTipoid());
        ordenCompra.setIdContacto(contacto);
        controladorOrdenCompra.create(ordenCompra); //creando orden de compra
        
       
//        List<DetalleOrden> listDetalleOrdenGuardar = new ArrayList<>(); 
//        //////*****Guardando Detalle de OrdenCompra*****////// 
//        for (int i = 0; i < jTableDetalleOrden.getRowCount(); i++) { 
//            DetalleOrden detalleOrdenCompra = new DetalleOrden();
//            detalleOrdenCompra.setIdOrdenCompra(ordenCompra);
//            detalleOrdenCompra.setIdProducto(listDetalleOrden.get(i).getIdProducto());
//            System.out.println(listDetalleOrden.get(i).getIdProducto());
//            detalleOrdenCompra.setGarantia(jTableDetalleOrden.getValueAt(i, 2).toString());
//            detalleOrdenCompra.setUnidad(jTableDetalleOrden.getValueAt(i, 3).toString());
//            detalleOrdenCompra.setCantidad(Integer.parseInt((String) jTableDetalleOrden.getValueAt(i,4)));
//            BigDecimal bd=new BigDecimal(jTableDetalleOrden.getValueAt(i,5).toString());   
//            detalleOrdenCompra.setPrecioorden(bd);
//            listDetalleOrdenGuardar.add(detalleOrdenCompra);           
//        }
//        ordenCompra.setDetalleOrdenList(listDetalleOrdenGuardar);        
//        controladorOrdenCompra.create(ordenCompra);       
//        JOptionPane.showMessageDialog(null, "Orden de Compra Registrada Correctamente", "Mensaje del Sistema", JOptionPane.INFORMATION_MESSAGE);
        
       
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButtonListProductos;
    private javax.swing.JComboBox jComboBoxArea;
    private javax.swing.JComboBox jComboBoxComprobPago;
    private javax.swing.JComboBox jComboBoxCondicionPago;
    private javax.swing.JComboBox jComboBoxContacto;
    private javax.swing.JComboBox jComboBoxElaboradox;
    private javax.swing.JComboBox jComboBoxMoneda;
    private javax.swing.JComboBox jComboBoxProveedor;
    private javax.swing.JComboBox jComboBoxRefeCompra;
    private javax.swing.JComboBox jComboBoxSolicitante;
    private com.toedter.calendar.JDateChooser jDateChooserEntrega;
    private com.toedter.calendar.JDateChooser jDateChooserEnvio;
    private com.toedter.calendar.JDateChooser jDateChooserRecepcion;
    private com.toedter.calendar.JDateChooser jDateChooserSolicitud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDetalleOrden;
    private javax.swing.JTextField txtProyecto;
    private javax.swing.JTextField txtSupervisor;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtigv;
    private javax.swing.JTextField txtnumorden;
    private javax.swing.JTextField txtsubtotal;
    // End of variables declaration//GEN-END:variables

    AreaJpaController controladorArea = new AreaJpaController();
    TrabajadorJpaController controladorTrabajador = new TrabajadorJpaController();
    ProveedorJpaController controladorProveedor = new ProveedorJpaController();
    ContactoJpaController controladorContacto = new ContactoJpaController();
    DetalleOrdenJpaController controladorDetalleOrden = new DetalleOrdenJpaController();
    OrdenCompraJpaController controladorOrdenCompra = new OrdenCompraJpaController();
    
     
    @Override
    public void presentarDatos() {
        List<Area> listTipoareas = controladorArea.findAreaEntities();
        List<Trabajador> listTrabajadores = controladorTrabajador.findTrabajadorEntities();
        List<Proveedor> listProveedor = controladorProveedor.findProveedorEntities();
        for (Area listtipoarea1 : listTipoareas) {jComboBoxArea.addItem(new ClaseJcombobox(listtipoarea1.getNombre(), listtipoarea1.getIdArea()));}
        for (Trabajador listTrabajador1 : listTrabajadores) {jComboBoxElaboradox.addItem(new ClaseJcombobox(listTrabajador1.getApellidos()+" "+listTrabajador1.getNombres(), listTrabajador1.getIdTrabajador()));}
        for (Proveedor listProveedor1 : listProveedor) {jComboBoxProveedor.addItem(new ClaseJcombobox(listProveedor1.getRazonsocial(), listProveedor1.getIdProveedor()));}
        
    }

    @Override
    public void llenarCampos(Object objeto) {        
    }

    @Override
    public void presentarDatos(String opcion) {
        if (opcion.equals("TablaDetalleOrden")) {
            listDetalleOrden = ObservableCollections.observableList(listDetalleOrden);
            MT_DetalleOrden mt = new MT_DetalleOrden(listDetalleOrden);
            listDetalleOrden.addObservableListListener(mt);
            this.jTableDetalleOrden.setModel(mt);
        }
    }

    @Override
    public void llenarCampos(String opcion, Object objeto) {
        if (opcion.equals("Pedido")) {
            DetalleOrden odetalleorden = new DetalleOrden();
            odetalleorden.setIdProducto((Producto) objeto);
            odetalleorden.setUnidad("Unid.");           
            this.listDetalleOrden.add(odetalleorden);            
        }
    }

    @Override
    public void limpiarFormulario() {
       
    }  
    
    public void setAnchoColumnas(){        
        jTableDetalleOrden.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        TableColumnAdjuster tca = new TableColumnAdjuster(jTableDetalleOrden);
        tca.adjustColumns();
        
    }
    

}
